language: python
python:
  - "3.8"

sudo: required

services:
  - docker

before_script:
  - sudo chmod -R 777 .
  - pip install docker-compose

script:
  - docker-compose run --rm unotesapi sh -c "python3 manage.py test"