# Generated by Django 3.0.3 on 2020-03-09 13:53

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteBookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(null=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(null=True, upload_to=core.models.users_upload)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('note_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.NoteBookModel')),
            ],
            options={
                'ordering': ['sort'],
                'unique_together': {('note_book', 'sort')},
            },
        ),
        migrations.AddField(
            model_name='notebookmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_books', to='core.UserProfileModel'),
        ),
        migrations.AlterUniqueTogether(
            name='notebookmodel',
            unique_together={('user', 'sort')},
        ),
        migrations.CreateModel(
            name='NoteAttachmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField(null=True)),
                ('file', models.FileField(upload_to=core.models.attachment_upload, validators=[core.models.filesize])),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.NoteModel')),
            ],
            options={
                'ordering': ['sort'],
                'unique_together': {('note', 'sort')},
            },
        ),
    ]
