# Generated by Django 3.0.3 on 2020-03-09 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemodel',
            old_name='note_book',
            new_name='notebook',
        ),
        migrations.AlterField(
            model_name='notebookmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='core.UserProfileModel'),
        ),
        migrations.AlterUniqueTogether(
            name='notemodel',
            unique_together={('notebook', 'sort')},
        ),
    ]
